### ISSUE TITLE
back cover not there?

### ISSUE THREAD

**Issue by geoff-hom-gmail-com** [m-ender/gloomhaven-rules#3]
it's listed in the ToC and obviously is really important, but I don't see it. Similarly, p. 2 of the rulebook isn't there! So I do like, *the first scenario* and can't tell what the treasure is.

**Comment by m-ender** [comment]
Yeah, the back cover seemed like a huge amount of pain to add, but I don't think there's anything really useful on page 2? Not sure what you mean by the first scenario treasure.

**Comment by geoff-hom-gmail-com** [comment]
Thanks for the quick reply and all your hard work. I was trying to use your rules as a complete replacement for the 70 mb rulebook, but it failed because of what I mentioned. But I understand things being too much effort for a volunteer. 

So, the first scenario treasure is a random side scenario. But it doesn't say that; it just shows a picture of the back of a card. And I didn't remember what it was called, so I tried searching in your rulebook. I recalled that on page 2 it lists all the card types and what they are. And I thought maybe that was on the back page, too. I see now that you list the rules for "random side scenario," but that didn't help me in my case because I didn't know what the card was called. (I thought "random dungeon," or "random scenario," but notice that neither search will work in this case. And "scenario" pops up too many times on its own.)

It doesn't help that the rulebook (v3, i.e., latest) lists those cards on p. 2 as "random scenario cards," but searching for that doesn't help because it's later called "random side scenarios." 

Anyway, I'm just writing this for the record. Thanks for all your hard work. Though with the back page missing, that is crucial, I feel. So I won't use this in place of the official rulebook, which means I won't use this at all.

**Comment by m-ender** [comment]
I'm happy to accept pull requests with either of these pages, but I currently don't have the bandwidth to add them myself.

As for the treasure being listed only as an image of the card, I'm really confused where you're seeing that? The treasure index at the end of the scenario book just says "Random Side Scenario" in words.

**Comment by geoff-hom-gmail-com** [comment]
Treasure: Doh! You must be right. I'm playing on TTS with the Fantasy mod. (I was playing the physical version at a friend's, before COVID, and then I moved…) In the mod, there's a "treasure deck" for each numbered treasure. And for #7 (scenario 1), it just shows the image. 

As for pull requests, I'm embarrassed as a coder to say I'm not sure how to do that, but I'll work on it. I can at least provide an image file of p. 2 and the last page at different resolutions, and you could pick one if you like it and at least provide that. Ball in my court.

**Comment by geoff-hom-gmail-com** [comment]
Ok, I submitted 3 pull requests. This was the first time I ever forked (and branched) a repository, and my first pull requests. Any feedback is welcome.

**Comment by m-ender** [comment]
Thanks! I'll try to review these over the next few days.

**Comment by m-ender** [comment]
All merged. Thanks a lot for your help with these!

**Comment by geoff-hom-gmail-com** [comment]
You're welcome! I learned a lot, too! Win-win!
